### ISSUE TITLE
[Infra/FEAT] Kubernetes Nginx Ingress로 각 마이크로서비스 라우팅

### ISSUE THREAD

**Issue by ChoiYoungHa** [Picktartup/Picktartup-backend#12]
## 💦 관련 이슈
#1 

## ✨ 기능 설명
> userservie, coinservice, contractservice, startupservice, walletservice, adminservice 각각의 서비스를 내부에서 rest 통신할 수 있도록 온프레미스 k8s 환경에 Nginx Ingress 라우팅 작업

## ⚠️ 중요도
> 중요도는 1 ~ 5로 나누어져 있으며, 숫자가 높을수록 중요도가 높습니다. 
>- 5: 긴급한 사항으로, 당장 개발 진행 필요

## ☑️ 작업 상세 내용
- [x] 매니페스트 파일 각각의 마이크로서비스 마다 작성
  - [x] deploy.yaml, statefulset.yaml, service.yaml, hap.yaml, exteranl-service.yaml
  - [x] Ingress.yaml 작성
- [x] Ingress-Nginx-Contoller Helm 설치

## 📎 작업내역 요약
**마이크로서비스, 공통설정, 미들웨어 등으로 매니페스트 파일 Gitops 관리**
![image](https://github.com/user-attachments/assets/465d1beb-2861-4c97-8996-c68536d0c8fd)

**Ingress 설정**
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservices-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/add-base-url: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, PUT, POST, DELETE, PATCH, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-busy-buffers-size: "512k"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "256k"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
spec:
  ingressClassName: nginx
  rules:
  # 도메인 기반 규칙
  - host: picktartup.local
    http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: front-external
            port:
              number: 80
      - path: /contract/(.*)
        pathType: Prefix
        backend:
          service:
            name: contract-external
            port:
              number: 80
      - path: /user/(.*)
        pathType: Prefix
        backend:
          service:
            name: user-external
            port:
              number: 80
      - path: /startup/(.*)
        pathType: Prefix
        backend:
          service:
            name: startup-external
            port:
              number: 80
      - path: /wallet/(.*)
        pathType: Prefix
        backend:
          service:
            name: wallet-external
            port:
              number: 80
      - path: /coin/(.*)
        pathType: Prefix
        backend:
          service:
            name: coin-external
            port:
              number: 80
      - path: /admin/(.*)
        pathType: Prefix
        backend:
          service:
            name: admin-external
            port:
              number: 80
      - path: /kibana/(.*)
        pathType: Prefix
        backend:
          service:
            name: kibana-external
            port:
              number: 5601
```

**ingress-nginx-controller helm 설치**
```cmd
helm install ingress-nginx ingress-nginx/ingress-nginx \
  --namespace ingress-nginx \
  --set controller.hostNetwork=true \
  --set controller.dnsPolicy=ClusterFirstWithHostNet
```
