### ISSUE TITLE
[Infra/BUG] 젠킨스가 docker socket에 접근하지 못하여 build 실패

### ISSUE THREAD

**Issue by ChoiYoungHa** [Picktartup/Picktartup-backend#8]
## #️⃣ 연관된 이슈
#4 

## #️⃣ 어떤 버그인가요?
![image](https://github.com/user-attachments/assets/6b65034e-ab7c-44eb-9dff-5314d5799337)
> 젠킨스 docker build 실패

## #️⃣ 어떤 상황에서 발생한 버그인가요?

> given - jenkins 파이프라인 실행
when - build 스테이지 실행중 docker build 실패
then - 에러발생

## #️⃣ 예상 결과

> docker image build 후 ECR 업로드

## #️⃣ 실제 결과

> docker build 실패
## 🐞트러블 슈팅

jenkins 컨테이너와 호스트의 docker socket을 공유하도록 설정 젠킨스 컨테이너에는 docker cli만 설치하여 경량화한다.

**docker-compose.yml**
```
version: '3'
services:
  jenkins:
    build: .
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    group_add:
      - "999"  # 호스트의 docker 그룹 GID

volumes:
  jenkins_home:
```

**dockerfile**
```
FROM jenkins/jenkins:lts

USER root

RUN apt-get update && \
    apt-get install -y \
    curl \
    unzip \
    apt-transport-https \
    ca-certificates \
    gnupg \
    lsb-release \
    && rm -rf /var/lib/apt/lists/*

# Docker 리포지토리 추가
RUN curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg && \
    echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | \
    tee /etc/apt/sources.list.d/docker.list > /dev/null

# AWS CLI 설치
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install && \
    rm -rf aws awscliv2.zip

# docker cli만 설치 (엔진은 호스트 것 사용)
RUN apt-get update && \
    apt-get install -y docker-ce-cli


# Jenkins 플러그인 설치
COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN jenkins-plugin-cli -f /usr/share/jenkins/ref/plugins.txt

USER jenkins
```

**plugin.txt**
```
git:latest
github:latest
workflow-aggregator:latest
docker-workflow:latest
pipeline-aws:latest
amazon-ecr:latest
credentials-binding:latest
gradle:latest
```
docker cli 설치 및 플러그인 포함하여 jenkins 컨테이너 다시 실행
